package main

import (
	"encoding/xml"
	"fmt"
	"os"
	"strconv"

	"github.com/STARRY-S/zip"
)

// https://anansi-project.github.io/docs/comicinfo/schemas/v2.0

type ComicInfo struct {
	Title       string `xml:"Title"`
	Series      string `xml:"Series"`
	Number      string `xml:"Number"`
	Summary     string `xml:"Summary"`
	Notes       string `xml:"Notes"`
	Year        int    `xml:"Year"`
	Month       int    `xml:"Month"`
	Day         int    `xml:"Day"`
	Writer      string `xml:"Writer"`
	Web         string `xml:"Web"`
	LanguageISO string `xml:"LanguageISO"`
}

func UpsertComicInfo(cbzPath string, info ComicInfo) error {
	// Open zip for updating
	f, err := os.OpenFile(cbzPath, os.O_RDWR, 0)
	if err != nil {
		return err
	}
	zu, err := zip.NewUpdater(f)
	if err != nil {
		return err
	}
	defer zu.Close()

	// Append ComicInfo.xml
	w, err := zu.Append("ComicInfo.xml", zip.APPEND_MODE_OVERWRITE)
	if err != nil {
		return err
	}
	encoder := xml.NewEncoder(w)
	encoder.Indent("", "  ")
	err = encoder.Encode(info)
	if err != nil {
		return err
	}

	return nil
}

func CreateComicInfo(cfg Config, number int) ComicInfo {
	return ComicInfo{
		Title:       fmt.Sprintf("Volume #%d", number),
		Writer:      cfg.Writer,
		LanguageISO: cfg.LanguageIso,
		Year:        cfg.FirstDate.Year(),
		Month:       int(cfg.FirstDate.Month()),
		Day:         cfg.FirstDate.Day(),
		Web:         cfg.Homepage,
		Summary:     cfg.Summary,
		Series:      cfg.Title,
		Number:      strconv.Itoa(number),
		Notes:       "Generated by github.com/liampulles/webcomic2cbz",
	}
}
